[mypy]
python_version = 3.12
plugins = mypy_django_plugin.main

explicit_package_bases = True
check_untyped_defs = True
warn_unused_ignores = True
warn_redundant_casts = True
show_error_codes = True

exclude = (?x)(
    ^\.venv[\\/]
    | [\\/]migrations[\\/]
    | ^manage\.py$
    )

[mypy.plugins.django-stubs]
django_settings_module = config.settings
strict_settings = True