# Generated by Django 5.2.16 on 2026-07-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrecipitationMeasurement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("measurement_date", models.DateField(unique=True, verbose_name="Data pomiaru")),
                ("snow", models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Opad śniegu")),
                ("rain", models.DecimalField(decimal_places=2, max_digits=6, verbose_name="opad deszczu")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Utworzono")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Zaktualizowano")),
            ],
            options={
                "verbose_name": "Pomiar opadów",
                "verbose_name_plural": "Pomiary opadów",
                "ordering": ["measurement_date"],
                "get_latest_by": "measurement_date",
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("snow__gte", 0)), name="weather_snow_gte_0"),
                    models.CheckConstraint(condition=models.Q(("rain__gte", 0)), name="weather_rain_gte_0"),
                ],
            },
        ),
    ]
