# Generated by Django 5.2.16 on 2026-07-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="precipitationmeasurement",
            table="weather_precipitation_measurement",
        ),
    ]
